### ISSUE TITLE
Using "?" in the derivation name is not ideal

### ISSUE THREAD

**Issue by cideM** [nix-community/npmlock2nix#118]
When making a valid derivation name in https://github.com/nix-community/npmlock2nix/blob/master/internal.nix#L33 a `?` character is chosen as a fall back. This can cause several errors in the succeeding Nix calls. For example, the Bash code often does not properly quote variables, which, in the case of `?`, leads to incorrect file names, since the `?` is interpreted as a wildcard. This issue is easy to fix by just adding quotes. But I then ran into another issue where the stack trace lead to [this line](https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/setup.sh#L163). I suspect that the derivation name somehow ends up as `$3`.

Looong story short: why not use a more file name friendly fallback character or just drop invalid characters? Also, the package name that I am dealing with is something like `@foo/bar` which got turned into `?foo?bar` or something like it.

I can provide a reproducible example if the problem is not already clear from the description.

**Comment by Infinisil** [comment]
This is now resolved with https://github.com/nix-community/npmlock2nix/pull/150
